#!/usr/bin/env php
<?php
defined('VENDOR_PATH') or define('VENDOR_PATH', __DIR__ . '/../../');
defined('VENDOR_MIGRATION_PATH') or define('VENDOR_MIGRATION_PATH', __DIR__);
defined('APP_MIGRATION_PATH') or define('APP_MIGRATION_PATH', __DIR__ . '/../../../migration');

require VENDOR_PATH . 'autoload.php';

// 配置文件
$config = require APP_MIGRATION_PATH . '/config/config.php';
$app = new \newx\migration\base\Command($config, $argv);
$app->run();